---
- name: Configure SQL Server Service for Automatic Startup
  win_service:
    name: MSSQLSERVER
    start_mode: auto
    state: started
    username: '{{sqluser}}'
    password: '{{sqlpassword}}'
  become: yes

- name: Configure SQL Server Agent Service for Automatic Startup
  win_service:
    name: SQLSERVERAGENT
    start_mode: auto
    state: started
    username: '{{sqluser}}'
    password: '{{sqlpassword}}'
  become: yes
